//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Linehaul
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Linehaul()
        {
            this.LINEHAUL_ORDER = new HashSet<LINEHAUL_ORDER>();
            this.Linehaul_Package = new HashSet<Linehaul_Package>();

            this.Staff = new Staff();
            this.Staff1 = new Staff();
        }

        [Key]
        [DisplayName("Mã chuyến xe")]
        [Required(ErrorMessage = "Mục này không được để trống!")]
        [StringLength(15, ErrorMessage = "Mục này không được nhập quá 15 ký tự")]
        public string LinehaulID { get; set; }

        [DisplayName("Biển số")]
        [Required(ErrorMessage = "Mục này không được để trống!")]
        [StringLength(10, ErrorMessage = "Mục này không được nhập quá 10 ký tự")]
        public string VehicleNumber { get; set; }

        [DisplayName("Số kiện hàng")]
        [Required(ErrorMessage = "Mục này không được để trống!")]
        [Range(0, int.MaxValue, ErrorMessage = "Số lượng phải lớn hơn 0")]
        public int NumberOfPackage { get; set; }

        [DisplayName("Số đơn lẻ")]
        [Required(ErrorMessage = "Mục này không được để trống!")]
        [Range(0, int.MaxValue, ErrorMessage = "Số lượng phải lớn hơn 0")]
        public int NumberOfOrder { get; set; }

        [DisplayName("Mã niêm phong")]
        [Required(ErrorMessage = "Mục này không được để trống!")]
        [StringLength(50, ErrorMessage = "Mục này không được nhập quá 50 ký tự")]
        public string Seal { get; set; }

        [DisplayName("NV thao tác")]
        [Required(ErrorMessage = "Mục này không được để trống!")]
        [StringLength(10, ErrorMessage = "Mục này không được nhập quá 10 ký tự")]
        public string Operator { get; set; }

        [DisplayName("NV lái xe")]
        [Required(ErrorMessage = "Mục này không được để trống!")]
        [StringLength(10, ErrorMessage = "Mục này không được nhập quá 10 ký tự")]
        public string Driver { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LINEHAUL_ORDER> LINEHAUL_ORDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Linehaul_Package> Linehaul_Package { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Staff Staff1 { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
