//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryManagement.Models
{
    using DeliveryManagement.Helper;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.LINEHAUL_ORDER = new HashSet<LINEHAUL_ORDER>();
            this.Order_Status = new HashSet<Order_Status>();
            this.OrderItems = new HashSet<OrderItem>();
            this.OrderProblems = new HashSet<OrderProblem>();
            this.Package_Order = new HashSet<Package_Order>();
        }

        //This method for sending blank data to View
        public Order(string id, string currentStation, string creator, bool onDelivering)
        {
            this.OrderID = id;
            this.Fee = 0;
            this.Paid = false;
            this.TotalWeight = 0.1;
            this.CurrentStationID = currentStation;
            this.Creator = creator;
            this.OnDelivering = onDelivering;
        }

        //This method for adding a temp record to DB
        public Order(string id, string currentStation, string creator)
        {
            this.OrderID = id;
            this.SenderName = Constants.defaultString;
            this.SenderAddress = Constants.defaultString;
            this.SenderPhone = Constants.defaultString;
            this.ReceiverName = Constants.defaultString;
            this.ReceiverAddress = Constants.defaultString;
            this.ReceiverPhone = Constants.defaultString;
            this.Fee = 0;
            this.Paid = false;
            this.TotalWeight = 0.1;
            this.CurrentStationID = currentStation;
            this.Creator = creator;
            this.OnDelivering = false;
        }

        [Key]
        [DisplayName("Mã đơn")]
        [Required(ErrorMessage = "Mục này không được để trống!")]
        [StringLength(15, ErrorMessage = "Mục này không được nhập quá 15 ký tự")]
        public string OrderID { get; set; }

        [DisplayName("Người gửi")]
        [Required(ErrorMessage = "Mục này không được để trống!")]
        [StringLength(50, ErrorMessage = "Mục này không được nhập quá 50 ký tự")]
        public string SenderName { get; set; }

        [DisplayName("Địa chỉ gửi")]
        [Required(ErrorMessage = "Mục này không được để trống!")]
        [StringLength(200, ErrorMessage = "Mục này không được nhập quá 200 ký tự")]
        public string SenderAddress { get; set; }

        [DisplayName("SĐT gửi")]
        [Required(ErrorMessage = "Mục này không được để trống!")]
        [StringLength(20, ErrorMessage = "Mục này không được nhập quá 20 ký tự")]
        public string SenderPhone { get; set; }

        [DisplayName("Email người gửi")]
        [StringLength(50, ErrorMessage = "Mục này không được nhập quá 50 ký tự")]
        public string SenderEmail { get; set; }

        [DisplayName("Người nhận")]
        [Required(ErrorMessage = "Mục này không được để trống!")]
        [StringLength(50, ErrorMessage = "Mục này không được nhập quá 50 ký tự")]
        public string ReceiverName { get; set; }

        [DisplayName("Địa chỉ nhận")]
        [Required(ErrorMessage = "Mục này không được để trống!")]
        [StringLength(200, ErrorMessage = "Mục này không được nhập quá 200 ký tự")]
        public string ReceiverAddress { get; set; }

        [DisplayName("SĐT nhận")]
        [Required(ErrorMessage = "Mục này không được để trống!")]
        [StringLength(20, ErrorMessage = "Mục này không được nhập quá 20 ký tự")]
        public string ReceiverPhone { get; set; }

        [DisplayName("Trạm gửi")]
        [StringLength(4)]
        public string FirstStation { get; set; }

        [DisplayName("Trung chuyển")]
        [StringLength(4)]
        public string Transit { get; set; }

        [DisplayName("Trạm giao")]
        [StringLength(4)]
        public string LastStation { get; set; }

        [DisplayName("Cước phí")]
        [DisplayFormat(DataFormatString = "{0: ## ### ##0.## đ}")]
        [Required(ErrorMessage = "Mục này không được để trống!")]
        [Range(0, double.MaxValue, ErrorMessage = "Giá phải lớn hơn 0")]
        public double Fee { get; set; }

        [DisplayName("Trạng thái thanh toán")]
        public bool Paid { get; set; }

        [DisplayName("Tổng KL")]
        [DisplayFormat(DataFormatString = "{0: ## ### ##0.## (kg)}")]
        [Required(ErrorMessage = "Tổng KL không được để trống và phải lớn hơn 0.1 kg!")]
        [Range(0, double.MaxValue, ErrorMessage = "Khối lượng phải lớn hơn 0")]
        public double TotalWeight { get; set; }

        [DisplayName("Giá trị hàng hóa")]
        [DisplayFormat(DataFormatString = "{0: ## ### ##0.## đ}")]
        [Range(0, double.MaxValue, ErrorMessage = "Phải nhập số lớn hơn 0")]
        public Nullable<double> OrderPrice { get; set; }

        [DisplayName("Đang ở trạm")]
        [Required(ErrorMessage = "Trạm hiện hành không được để trống!")]
        [StringLength(4)]
        public string CurrentStationID { get; set; }

        [DisplayName("Người tạo")]
        [Required(ErrorMessage = "Người tạo đơn không được để trống!")]
        [StringLength(10, ErrorMessage = "Mục này không được nhập quá 10 ký tự")]
        public string Creator { get; set; }

        [DisplayName("Đang vận chuyển")]
        public bool OnDelivering { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LINEHAUL_ORDER> LINEHAUL_ORDER { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Station Station { get; set; }
        public virtual Station Station1 { get; set; }
        public virtual Station Station2 { get; set; }
        public virtual Station Station3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Status> Order_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProblem> OrderProblems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Package_Order> Package_Order { get; set; }
    }
}
