//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Status
    {
        public string OrderID { get; set; }
        public string StatusID { get; set; }
        public string StationID { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Station Station { get; set; }
        public virtual Status Status { get; set; }
    }
}
