//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Order_Status
    {
        public Order_Status() { }
        public Order_Status(string orderId, string statusId, string stationId, System.DateTime time)
        {
            this.OrderID = orderId;
            this.StatusID = statusId;
            this.StationID = stationId;
            this.Time = time;
        }

        [Key]
        [DisplayName("Mã đơn")]
        [Required(ErrorMessage = "Mục này không được để trống!")]
        [Column(Order = 0)]
        [StringLength(15, ErrorMessage = "Mục này không được nhập quá 15 ký tự")]
        public string OrderID { get; set; }

        [Key]
        [DisplayName("Mã trạng thái")]
        [Required(ErrorMessage = "Mục này không được để trống!")]
        [Column(Order = 1)]
        [StringLength(10, ErrorMessage = "Mục này không được nhập quá 10 ký tự")]
        public string StatusID { get; set; }

        [Key]
        [DisplayName("Mã trạm")]
        [Required(ErrorMessage = "Mục này không được để trống!")]
        [StringLength(4)]
        public string StationID { get; set; }

        [Key]
        [DisplayName("TG cập nhật")]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy HH:mm:ss}")]
        [Required(ErrorMessage = "Mục này không được để trống!")]
        public System.DateTime Time { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Station Station { get; set; }
        public virtual Status Status { get; set; }
    }
}
