//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProblem
    {
        public string OrderID { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string Status { get; set; }
        public bool IsDisposed { get; set; }
        public bool Continuable { get; set; }
        public string ReportStaff { get; set; }
        public string DisposedStaff { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Staff Staff1 { get; set; }
    }
}
