//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class OrderItem
    {
        public OrderItem() { }
        public OrderItem(string orderID, int itemID, int quantity)
        {
            this.OrderID = orderID;
            this.ItemID = itemID;
            this.Quantity = quantity;
        }

        [Key]
        [DisplayName("Mã đơn")]
        [Required(ErrorMessage = "Mục này không được để trống!")]
        [Column(Order = 0)]
        [StringLength(15, ErrorMessage = "Mục này không được nhập quá 15 ký tự")]
        public string OrderID { get; set; }

        [Key]
        [DisplayName("STT")]
        [Required(ErrorMessage = "Mục này không được để trống!")]
        [Column(Order = 1)]
        public int ItemID { get; set; }

        [DisplayName("Tên SP")]
        [Required(ErrorMessage = "Mục này không được để trống!")]
        [StringLength(50, ErrorMessage = "Mục này không được nhập quá 50 ký tự")]
        public string ItemName { get; set; }

        [DisplayName("Số lượng")]
        [Required(ErrorMessage = "Mục này không được để trống!")]
        [Range(1, int.MaxValue, ErrorMessage = "Số lượng phải lớn hơn 0")]
        public int Quantity { get; set; }

        [DisplayName("Khối lượng (kg)")]
        [Required(ErrorMessage = "Mục này không được để trống!")]
        [Range(0.1, double.MaxValue, ErrorMessage = "Khối lượng tối thiểu là 0.1kg")]
        public double Weight { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
