//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Package()
        {
            this.Linehauls = new HashSet<Linehaul>();
            this.Orders = new HashSet<Order>();
        }
    
        public string PackageID { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> CompleteTime { get; set; }
        public int NumberOfOrder { get; set; }
        public string StatusID { get; set; }
        public double TotalWeight { get; set; }
        public string Packer { get; set; }
        public string SendingStation { get; set; }
        public string ReceivingStation { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual Station Station { get; set; }
        public virtual Station Station1 { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Linehaul> Linehauls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
