//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Package_Order
    {
        public Package_Order() { }
        public Package_Order(string packageID) 
        {
            this.PackageID = packageID;
        }

        [Key]
        [DisplayName("Mã kiện hàng")]
        [Required(ErrorMessage = "Mục này không được để trống!")]
        [StringLength(15, ErrorMessage = "Mục này không được nhập quá 15 ký tự")]
        public string PackageID { get; set; }

        [Key]
        [DisplayName("Mã đơn")]
        [Required(ErrorMessage = "Mục này không được để trống!")]
        [StringLength(15, ErrorMessage = "Mục này không được nhập quá 15 ký tự")]
        public string OrderID { get; set; }

        [DisplayName("TG thêm")]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy HH:mm:ss}")]
        [Required(ErrorMessage = "Mục này không được để trống!")]
        public System.DateTime AddTime { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Package Package { get; set; }
    }
}
