//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingRate
    {
        public string SendingStation { get; set; }
        public string ReceivingStation { get; set; }
        public double MinPrice { get; set; }
        public double PricePerKg { get; set; }
        public Nullable<double> MinPriceForHVO { get; set; }
        public Nullable<double> PricePerKgForHVO { get; set; }
    
        public virtual Station Station { get; set; }
        public virtual Station Station1 { get; set; }
    }
}
