//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.Linehauls = new HashSet<Linehaul>();
            this.Linehauls1 = new HashSet<Linehaul>();
            this.Orders = new HashSet<Order>();
            this.OrderProblems = new HashSet<OrderProblem>();
            this.OrderProblems1 = new HashSet<OrderProblem>();
            this.Packages = new HashSet<Package>();
        }

        [Key]
        [StringLength(10, ErrorMessage = "Mục này không được nhập quá 10 ký tự")]
        [DisplayName("Mã NV")]
        [Required(ErrorMessage = "Mã nhân viên không được để trống!")]
        public string StaffID { get; set; }

        [DisplayName("Mật khẩu")]
        [Required(ErrorMessage = "Mật khẩu không được để trống!")]
        [DataType(DataType.Password)]
        [StringLength(20, ErrorMessage = "Mục này không được nhập quá 20 ký tự")]
        public string Password { get; set; }

        [DisplayName("Họ tên")]
        [Required(ErrorMessage = "Họ tên không được để trống!")]
        [StringLength(50, ErrorMessage = "Mục này không được nhập quá 50 ký tự")]
        public string Fullname { get; set; }

        [DisplayName("Giới tính")]
        public bool Male { get; set; }

        [DisplayName("Ngày sinh")]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}")]
        [Required(ErrorMessage = "Ngày sinh không được để trống!")]
        [Column(TypeName = "date")]
        public System.DateTime Birthday { get; set; }

        [DisplayName("Trạm/Bộ phận")]
        [Required(ErrorMessage = "Trạm/Đơn vị làm việc không được để trống!")]
        [StringLength(4)]
        public string StationID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Linehaul> Linehauls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Linehaul> Linehauls1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProblem> OrderProblems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProblem> OrderProblems1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Package> Packages { get; set; }
        public virtual Station Station { get; set; }
    }
}
