//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.Linehauls = new HashSet<Linehaul>();
        }

        [Key]
        [DisplayName("BKS")]
        [Required(ErrorMessage = "Mục này không được để trống!")]
        [StringLength(10, ErrorMessage = "Mục này không được nhập quá 10 ký tự")]
        public string VehicleNumber { get; set; }

        [DisplayName("Loại phương tiện")]
        [Required(ErrorMessage = "Mục này không được để trống!")]
        [StringLength(50, ErrorMessage = "Mục này không được nhập quá 50 ký tự")]
        public string Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Linehaul> Linehauls { get; set; }
    }
}
